### ISSUE TITLE
Server returns 404 when I hit http://localhost:3001/blogjs/app

### ISSUE THREAD

**Issue by nuweb** [kdelemme/blogjs#3]
The server doesn't serve static files without adding below line to blog.js
app.use('/blogjs/app', express.static(__dirname + '/../app'));

**Comment by psampath** [comment]
I tried to access the app with full path http://localhost:3001/path/to/blogjs/app. I still can't get it working.. Keep getting 404. do I have to do any other setup?

**Comment by psampath** [comment]
nvm.. figured it..
