### ISSUE TITLE
None of the pages are loading in the browser.

### ISSUE THREAD

**Issue by sri7vasu** [kdelemme/blogjs#30]
Hi,

I am able to start the application in the console successfully as below , but none of the pages are loading.

$ node blog.js
Blog API is starting on port 3001
Redis is ready
Connection successful to: mongodb://localhost/blog

None of the following pages are loading:

http://localhost:3001/blogjs/app

http://localhost:3001/blogjs/app/#/admin/register

http://localhost:3001/blogjs/app/#/admin/login

Please help. I am following your tutorial http://www.kdelemme.com/2014/03/09/authentication-with-angularjs-and-a-node-js-rest-api/ and trying to implement the same.

The demo http://projects.kdelemme.com/blog/app/#/ is not working too. Please help.

Thank you !

Regards,
Srini

**Comment by kdelemme** [comment]
Hey, you need to setup a HTTP server to serve the frontend app directory.

**Comment by sri7vasu** [comment]
Thank you for the immediate response. May i know how to do that exactly or can you update the same in your readme ? I am a beginner to the MEAN stack.

**Comment by kdelemme** [comment]
Assuming you are using linux debian or ubuntu: https://www.digitalocean.com/community/tutorials/how-to-configure-the-apache-web-server-on-an-ubuntu-or-debian-vps

Easy way:
install apache2, by default it looks for files inside /var/www/, so put the content of app/ inside /var/www

```
sudo apt-get install apache2
cd blogjs/
mv app/ /var/www/
```

go to http://localhost/app/ and it should work :)

**Comment by sri7vasu** [comment]
great, Thank you ! can i make it work using the npm http-server too ?
I am on windows.

**Comment by sri7vasu** [comment]
yup, able to make it work with http-server npm package.
> cd blogjs 
> npm install http-server

and then 
> http-server 

Now it's loading all the pages.
